version: '3'
services:

  frontend:
    build:
      context: ""
      dockerfile: docker/Dockerfile.frontend
    image: "frontend"
    hostname: frontend
    volumes:
      - ${PWD}/frontend:/src:cached
    ports:
      - "8080:3000"

volumes:
  db_data:
